### ISSUE TITLE
Build the GUI for the notebook

### ISSUE THREAD

**Issue by Kets1596** [ECU-CSCI-4230/SpiralBound#10]

**Comment by KuraideWolfie** [comment]
Updated List of Todo:
- [ ] Remove save, load from the shortcut bar, and move the shortcut bar into the window in the TextEditor tab with bold, italic, etc shortcuts for formatting
- [ ] Remove 'Format' from the menubar
- [ ] (Optional) Shortcut keys for bolding and such

**Comment by CirkuitBreaker** [comment]
Since format menu changes are being moved to their own issue (#20), this is closed.
