### ISSUE TITLE
File and Code Standardization

### ISSUE THREAD

**Issue by CirkuitBreaker** [ECU-CSCI-4230/SpiralBound#19]
- [x] Remove `event.cpp` from the source files (unused)
- [x] Remove `addpage.ui` from source (unused)
- [x] Remove `thewidgetitem.h` from source (unused)
- [x] Rename GUI widgets to conform to standards **type_name**
  - [x] tabWidget_2
  - [ ] textEdit
- [x] Clean up unused icons from resources

**Comment by KuraideWolfie** [comment]
tabWidget_2 is no longer a problem due to a switch from a list widget to a tree widget. This has been checked off.

**Comment by KuraideWolfie** [comment]
Because the textEdit widget was changed to a plainTextEdit widget, this issue is closed.
