### ISSUE TITLE
Section Customization Window and Color

### ISSUE THREAD

**Issue by CirkuitBreaker** [ECU-CSCI-4230/SpiralBound#21]
Create a window for section customization that has:
- Section name editing
- Section color editing

Also perform the following two tasks:
- [ ] Section color should be duller if a tab isn't selected
- [x] Modify the section API to:
  - [x] Store section color
  - [x] Save section color / load section color

**Comment by KuraideWolfie** [comment]
In regards to the 'duller color' point - this is no longer a requirement, due to the switch from list widget to tree widget.
