### ISSUE TITLE
Update Notebook Data Structure

### ISSUE THREAD

**Issue by CirkuitBreaker** [ECU-CSCI-4230/SpiralBound#22]
With the advent of a difference in the parsing of markdown to HTML versus a block-based format (such as Jupyter Notebooks), the following needs to be done:
- [x] Remove the Block.cpp/Block.h files from the source
- [x] Modify Page.cpp/Page.h to not reference the Block data structure

**Comment by KuraideWolfie** [comment]
Due to updates being made regarding the structure/widget used for viewing pages, the following updates have to also be made with the above:
- [ ] Remove description-based functions from the Section DS
- [ ] Remove references to description in the Section DS; reflect changes to QTextDocument
- [ ] Update Page DS to reference QTextDocument instance in save/load

**Comment by KuraideWolfie** [comment]
Commits c468ff5437298a0cfce0e79fd5d8bd3d9c65b633, 00af3fde5545a0860720ccd4769f50525232e69d, and aadbb6794c7e7bde9106f20f6348708dd65e7277 close this issue.

Results of the unit test to verify are as follows:
```
********* Start testing of TestBook *********
Config: Using QtTest library 5.12.0, Qt 5.12.0 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 7.3.0)
PASS   : TestBook::initTestCase()
  Searching string for 'a'
  Searching string for 'h' in reverse
  Testing Q->C strings
PASS   : TestBook::testUtil()
  Testing property equivalence
  Testing string conversion for book
PASS   : TestBook::testBookTF()
QDEBUG : TestBook::testSecTF() Color  "#ff00aa"

  Testing property equivalence
  Testing string conversion for section
PASS   : TestBook::testSecTF()
  Block separator is ¼
  Testing property equivalence
  Testing string conversion for page
PASS   : TestBook::testPgTF()
PASS   : TestBook::cleanupTestCase()
Totals: 6 passed, 0 failed, 0 skipped, 0 blacklisted, 12ms
********* Finished testing of TestBook *********
```
