### ISSUE TITLE
Rename Notebook Modal

### ISSUE THREAD

**Issue by KuraideWolfie** [ECU-CSCI-4230/SpiralBound#65]
**Ketu**:
- [x] Create a rename notebook dialog
 - Blank names are not acceptable (follow aforementioned notebook name scheme: `A-Za-z0-9-_`
- [x] Update the data structure with the new name
- [x] Prompt with an error if a notebook with the given name already exists

**Matt**:
- [x] Saving should reflect the new notebook name (delete the old notebook and resave the new name)

**Comment by Kets1596** [comment]
Hey Matthew,
I implemented all the requirements except the last one on the list (Saving should reflect the new notebook name (delete the old notebook and resave the new name).

**Comment by KuraideWolfie** [comment]
I setup the code to remove the old notebook and save the notebook under its new name; however, this yields an error, and additionally, yields another error with saving and loading in general. This will be explored in another issue. As for this one, it's closed.
